[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[build.variables]
NIXPACKS_NODE_ENV = "development"

[deploy]
startCommand = "npm run serve"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
